### ISSUE TITLE
Raising an error but doing nothing?

### ISSUE THREAD

**Issue by GDemay** [flowlord/encryption-by-mutilple-subtitution#2]
Je regardais ton projet et je ne comprends pas l'intérêt de faire un try except pour faire un pass
https://github.com/flowlord/encryption-by-mutilple-subtitution/blob/1cbc1561995993614ed9d50019dfc28783e3b9ed/tools.py#L53

**Comment by flowlord** [comment]
A ouais il se passe rien, bien vu je pensais qu'il allais dire que le fichier n'existait pas ;)
